(function(){
'use strict';
const Store=window.TerritoryStore;
const S=()=>Store?.state||{};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const enemyNames=[
 {name:'Лесной разбойник',icon:'🗡️',hp:180,atk:18,def:5,coins:45},
 {name:'Рудничный голем',icon:'🗿',hp:270,atk:23,def:12,coins:65},
 {name:'Рунный страж',icon:'🔮',hp:390,atk:29,def:18,coins:90},
 {name:'Элитный вождь',icon:'⚔️',hp:540,atk:36,def:24,coins:125}
];
let battle=null,busy=false;
function home(){return document.querySelector('#home.territory-home-modular')}
function q(s){return home()?.querySelector(s)}
function ensureState(){const s=S();s.pve=s.pve||{chapter:s.currentChapter||1,stage:s.chapterStage||1,progress:s.chapterProgress||0,bossPending:false,bossDefeated:0,wins:0};s.currentChapter=Math.max(1,Math.min(240,Number(s.currentChapter)||1));s.chapterProgress=Math.max(0,Math.min(100,Number(s.chapterProgress)||0));s.chapterStage=Math.max(1,Math.min(4,Number(s.chapterStage)||Math.floor(s.chapterProgress/25)+1));s.pve.chapter=s.currentChapter;s.pve.stage=s.chapterStage;s.pve.progress=s.chapterProgress;s.chapterBossUnlocked=!!(s.chapterBossUnlocked||s.pve.bossPending||s.chapterProgress>=100);return s}
function stats(){const s=S(),eq=Array.isArray(s.equipment)?s.equipment:[];let atk=125+(Number(s.level)||1)*2,def=98+(Number(s.level)||1),agi=101+(Number(s.level)||1),hp=Number(s.maxHp)||100,crit=8,dodge=5;for(const it of eq){if(!it||typeof it!=='object')continue;atk+=Number(it.attack??it.strength??it.damage??it.atk)||0;def+=Number(it.defense??it.def??it.armor??it.guard)||0;agi+=Number(it.agility??it.agi??it.speed)||0;hp+=Number(it.maxHp??it.hp??it.health)||0;crit+=Number(it.critChance)||0;dodge+=Number(it.dodgeChance)||0}return{atk,def,agi,hp,crit,dodge}}
function makeEnemy(stage,boss){const s=S(),lv=+s.level||1;if(boss){const hp=2600+lv*22;return{name:'Вождь Боевого Племени',icon:'👑',maxHp:hp,hp,atk:32+lv,def:20+Math.floor(lv/3),coins:500,boss:true}}const b=enemyNames[Math.max(0,Math.min(3,stage-1))],scale=1+(Math.max(0,+s.currentChapter-1)*.055),hp=Math.round(b.hp*scale+lv*8);return{...b,maxHp:hp,hp,atk:Math.round(b.atk*scale+lv*.6),def:Math.round(b.def+lv*.25),boss:false}}
function mountBattleUI(){if(!home())return;home().querySelector('.thm-battle')?.classList.add('active');}
function setSprite(which,boss){const el=q(which);if(!el)return;if(which==='.enemy-img')el.src='assets/skins/battle-enemy.svg';if(which==='.hero-img')el.src='assets/skins/battle-hero.svg';el.alt=which==='.enemy-img'?(boss?'Босс':'Противник'):'Герой'}
function paint(){const h=home();if(!h||!battle)return;const s=S(),t=stats(),e=battle.enemy;mountBattleUI();
 const set=(sel,val)=>{const el=q(sel);if(el)el.textContent=val};
 set('.battle-stage-label',battle.boss?'БОСС ГЛАВЫ':'БОЙ С БОТОМ');set('.battle-sub',battle.boss?'Последняя битва главы':'Следующий противник');set('.enemy-name',e.name);set('.enemy-hp',`${Math.max(0,Math.ceil(e.hp))}/${e.maxHp}`);set('.hero-name',s.profile?.displayName||'Герой');set('.hero-hp',`${Math.max(0,Math.ceil(battle.hp))}/${battle.maxHp}`);
 const eb=q('.enemy-bar .unit-fill'),hb=q('.hero-bar .unit-fill');if(eb)eb.style.width=Math.max(0,e.hp/e.maxHp*100)+'%';if(hb)hb.style.width=Math.max(0,battle.hp/battle.maxHp*100)+'%';q('.enemy-bar b')&&(q('.enemy-bar b').textContent=`${Math.max(0,Math.ceil(e.hp))}/${e.maxHp}`);q('.hero-bar b')&&(q('.hero-bar b').textContent=`${Math.max(0,Math.ceil(battle.hp))}/${battle.maxHp}`);
 const status=q('#thmBattleStatus');if(status)status.textContent=battle.auto?`Автобой ×${battle.speed}`:(battle.boss?`Фаза ${battle.phase} · ход ${battle.turn}`:(battle.started?`Ход ${battle.turn}`:'Готов к бою'));
 const result=q('#thmBattleResult');if(result)result.hidden=!battle.result;
 if(result&&battle.result){result.innerHTML=`<h3>${battle.result.win?(battle.boss?'👑 БОСС ПОВЕРЖЕН':'🏆 ПОБЕДА'):'☠️ ПОРАЖЕНИЕ'}</h3><p>${esc(battle.result.text)}</p>${battle.result.win?'<button id="thmNextBtn">Продолжить</button>':'<button id="thmRetryBtn">Повторить</button>'}`;document.querySelector('#thmNextBtn')?.addEventListener('click',()=>{result.hidden=true;nextAfterWin()});document.querySelector('#thmRetryBtn')?.addEventListener('click',()=>{result.hidden=true;startCurrent()});}
 setSprite('.enemy-img',battle.boss);setSprite('.hero-img',false);
 const sc=q('.stone-count');if(sc)sc.textContent=Math.max(0,(+s.battleStones||0)+(+s.battleStonesBonus||0));
 const auto=q('[data-home-action="auto"]');if(auto)auto.dataset.active=battle.auto||s.auto?'1':'0';const speed=q('[data-home-action="speed"]');if(speed)speed.dataset.speed=String(battle.speed||s.battleSpeed||s.speed||1);
}
function logBattle(msg,type='info'){const fx=q('#thmBattleEffects');if(!fx)return;const p=document.createElement('div');p.className=`battle-fx ${type}`;p.textContent=msg;fx.appendChild(p);setTimeout(()=>p.remove(),900)}
function showResult(win,text){if(!battle)return;battle.ended=true;battle.result={win,text};paint()}
function takeStone(s){if((+s.battleStones||0)>0){s.battleStones--;return true}if((+s.battleStonesBonus||0)>0){s.battleStonesBonus--;return true}return false}
async function start(stage,boss=false){if(busy)return;const s=ensureState();stage=Math.max(1,Math.min(4,Number(stage)||s.chapterStage));if(!boss&&s.chapterProgress>=100){openBoss();return}if(boss&&!s.chapterBossUnlocked){showInline('Сначала победи 4 ботов этой главы.');return}battle={stage,boss,started:false,server:false,enemy:makeEnemy(stage,boss),hp:Math.max(1,Number(s.hp)||Number(s.maxHp)||100),maxHp:Number(s.maxHp)||100,phase:1,turn:0,auto:!!s.auto,speed:Number(s.battleSpeed??s.speed)||1,ended:false,result:null};paint();
 if(window.TerritoryServer?.available?.()){busy=true;try{const r=await window.TerritoryServer.start(s.currentChapter,stage,boss);const c=r.combat||{};Object.assign(Store.state,r.state||{});battle.server=true;battle.session_id=r.session_id;battle.nonce=r.nonce;battle.enemy.maxHp=Number(c.enemyMaxHp)||battle.enemy.maxHp;battle.enemy.hp=Number(c.enemyHp)||battle.enemy.hp;battle.hp=Number(c.heroHp)||battle.hp;battle.maxHp=Number(c.maxHp)||battle.maxHp;Store.saveNow?.();busy=false;beginAction();return}catch(e){busy=false;showInline('Серверный бой недоступен. Используем локальный бой.')}}
 if(!takeStone(s)){showInline('🪨 Боевые камни закончились. Получи их за задания, награды, магазин и события.');return}Store.saveNow?.();beginAction()}
function beginAction(){battle.started=true;battle.ended=false;battle.result=null;paint();logBattle(battle.boss?'👑 Босс вышел!':'⚔️ Бой начался!','start');if(battle.auto)setTimeout(()=>action('attack'),battle.speed===2?220:520)}
async function action(kind){if(!battle||!battle.started||battle.ended||busy)return;busy=true;if(battle.server){try{const r=await window.TerritoryServer.action(battle.session_id,battle.nonce,kind),c=r.combat||{};battle.hp=Number(c.heroHp)||battle.hp;battle.maxHp=Number(c.maxHp)||battle.maxHp;battle.enemy.hp=Number(c.enemyHp)||battle.enemy.hp;battle.enemy.maxHp=Number(c.enemyMaxHp)||battle.enemy.maxHp;battle.turn=Number(c.turn)||battle.turn;logBattle(kind==='attack'?'⚔️ Удар':'✦ Умение',kind==='attack'?'hit':'skill');if(c.result==='win'||c.result==='lose'||c.ended){busy=false;await finish(c.result==='win');return}busy=false;paint();if(battle.auto)setTimeout(()=>action('attack'),battle.speed===2?220:520);return}catch(e){busy=false;logBattle('⚠️ Серверный бой: '+(e.message||'ошибка'),'bad');paint();return}}
 const s=S(),t=stats(),e=battle.enemy;let dmg=0;const crit=Math.random()<t.crit/100, dodge=Math.random()<Math.min(.3,e.def/700), base=Math.max(5,Math.round(t.atk*.72-e.def*.28+Math.random()*12));dmg=Math.round(base*(crit?1.8:1));if(kind==='skill:power')dmg=Math.round(dmg*1.7);if(!dodge)e.hp=Math.max(0,e.hp-dmg);battle.turn++;logBattle(dodge?'🛡 Уворот!':`-${dmg}${crit?' CRIT!':''}`,crit?'crit':'hit');if(e.hp<=0){busy=false;await finish(true);return}if(battle.boss){const pct=e.hp/e.maxHp;if(battle.phase===1&&pct<=.66){battle.phase=2;e.atk=Math.round(e.atk*1.2);e.def+=8;logBattle('🔥 Фаза 2','phase')}if(battle.phase===2&&pct<=.33){battle.phase=3;e.atk=Math.round(e.atk*1.25);logBattle('☠️ ЯРОСТЬ БОССА','phase')}}
 const incoming=Math.max(3,Math.round(e.atk*.45-t.def*.12+Math.random()*7)),enemyCrit=Math.random()<(.08+(battle.boss&&battle.phase===3?.07:0));const taken=Math.round(incoming*(enemyCrit?1.6:1));battle.hp=Math.max(0,battle.hp-taken);if(battle.hp<=0||battle.turn>=30){busy=false;await finish(false);return}busy=false;paint();if(battle.auto)setTimeout(()=>action('attack'),battle.speed===2?220:520)}
async function finish(win){battle.ended=true;const s=S();busy=false;if(battle.server){if(!win){s.hp=Math.max(1,Math.floor((s.maxHp||100)*.35));Store.saveNow?.();window.dispatchEvent(new CustomEvent('territory:pve-finished',{detail:{win:false,boss:!!battle.boss}}));showResult(false,'Герой пал. Подготовься и попробуй ещё раз.');return}try{const r=await window.TerritoryServer.complete(battle.session_id);Object.assign(Store.state,r.state||{});if(r.economy){s.coins=Number(r.economy.coins)||s.coins;s.gems=Number(r.economy.gems)||s.gems}Store.saveNow?.();window.dispatchEvent(new CustomEvent('territory:pve-finished',{detail:{win:true,boss:!!battle.boss}}));showResult(true,'Награда сервера получена.');return}catch(e){showResult(true,'Победа подтверждена, награда будет синхронизирована.');return}}
 if(win){if(battle.boss){s.coins=(+s.coins||0)+battle.enemy.coins;s.gems=(+s.gems||0)+5;s.currentChapter=Math.min(240,(+s.currentChapter||1)+1);s.chapterStage=1;s.chapterProgress=0;s.chapterBossUnlocked=false;s.chapterCompleted=true;s.pve={...(s.pve||{}),chapter:s.currentChapter,stage:1,progress:0,bossPending:false};s.forge=s.forge||{materials:0};s.forge.materials=(+s.forge.materials||0)+10;Store.trackProgress?.('bosses',1);Store.trackProgress?.('chapters',1);Store.addXp?.(60)}else{s.coins=(+s.coins||0)+battle.enemy.coins;s.pve.wins=(+s.pve.wins||0)+1;s.chapterProgress=Math.min(100,(+s.chapterProgress||0)+25);s.chapterStage=s.chapterProgress>=100?4:Math.min(4,(+s.chapterStage||1)+1);s.chapterBossUnlocked=s.chapterProgress>=100;s.pve.progress=s.chapterProgress;s.pve.stage=s.chapterStage;Store.trackProgress?.('wins',1);Store.addXp?.(25+battle.stage*5)}s.hp=Math.max(1,Math.floor(battle.hp));Store.saveNow?.();window.dispatchEvent(new CustomEvent('territory:pve-finished',{detail:{win:true,boss:!!battle.boss}}));showResult(true,battle.boss?'Глава завершена. Открыта следующая глава.':`+${battle.enemy.coins} 🪙 · следующий противник готов.`)}else{s.hp=Math.max(1,Math.floor((s.maxHp||100)*.35));Store.saveNow?.();window.dispatchEvent(new CustomEvent('territory:pve-finished',{detail:{win:false,boss:!!battle.boss}}));showResult(false,'Герой пал. Попробуй ещё раз.')}}
function nextAfterWin(){if(!battle)return;const s=ensureState(),wasBoss=battle.boss,nextStage=battle.stage;battle=null;paint();if(!wasBoss)setTimeout(()=>start(nextStage,false),220)}
function startCurrent(){const s=ensureState();start(Math.max(1,Math.min(4,s.chapterStage||1)),false)}
function openBoss(){const s=ensureState();if(!s.chapterBossUnlocked){showInline('☠️ Босс откроется после 4 побед в текущей главе.');return}start(4,true)}
function showInline(msg){const st=q('#thmBattleStatus');if(st){st.textContent=msg;st.classList.add('warn');setTimeout(()=>st.classList.remove('warn'),1800)}paint()}
function close(){battle=null;busy=false;paint();window.showScreen?.('home')}
function setAuto(){if(!battle)return;const s=S();battle.auto=!!s.auto;paint();if(battle.auto&&battle.started&&!battle.ended)action('attack')}
function setSpeed(){if(!battle)return;const s=S();battle.speed=Number(s.battleSpeed??s.speed)||1;paint()}
window.PvEFlow={open:()=>window.showScreen?.('map'),startRunner:startCurrent,openBoss,stop:close};
window.PvEBattle={start,startCurrent,attack:()=>battle&&!battle.started?beginAction():(battle?action('attack'):startCurrent()),skill:x=>battle&&!battle.started?beginAction():(battle?action('skill:'+(x||'power')):startCurrent()),close,setAuto,setSpeed};
window.addEventListener('territory:home-auto',setAuto);window.addEventListener('territory:home-speed',setSpeed);window.addEventListener('territory:state-changed',paint);
})();
