(()=>{const S=window.TerritoryStore;if(!S)return;
const E=()=>S.state.economy||(S.state.economy={v:5,res:{},prof:{blacksmith:{l:1,x:0},leatherworker:{l:1,x:0},jeweler:{l:1,x:0},runesmith:{l:1,x:0}},gear:[],runs:{active:null,history:[]},auction:{listings:[],sales:[]},contracts:[],ledger:[],daily:{date:"",claimed:false}});
const P={blacksmith:["Кузнец","⚒️"],leatherworker:["Кожевник","🪡"],jeweler:["Ювелир","💍"],runesmith:["Рунописец","🔮"]};
const M=[
["greenwood","Зелёный лес","🌲","Низкий",[["Древесина","wood"],["Смола","resin"],["Кожа","leather"]],1],
["ironmine","Железные рудники","⛏️","Низкий",[["Железная руда","iron_ore"],["Уголь","coal"],["Камень","stone"]],1],
["silverpeak","Серебряные вершины","🏔️","Средний",[["Серебро","silver_ore"],["Кристалл","crystal"],["Уголь","coal"]],1],
["runewastes","Рунические пустоши","🔮","Высокий",[["Осколок руны","rune_shard"],["Мана-кристалл","mana_crystal"],["Древняя пыль","ancient_dust"]],1],
["dragonvale","Долина драконов","🐉","Очень высокий",[["Чешуя дракона","dragon_scale"],["Кость дракона","dragon_bone"],["Огненное ядро","fire_core"]],2]
];
const REC=[
["iron_blade","⚔️","Железный клинок","blacksmith",1,{iron_ore:4,coal:2},{attack:8},35],
["iron_guard","🛡️","Железный щит","blacksmith",3,{iron_ore:5,stone:2},{defense:10},45],
["forest_boots","🥾","Лесные сапоги","leatherworker",1,{leather:5,resin:2},{hp:12},35],
["crystal_ring","💍","Кристальное кольцо","jeweler",5,{silver_ore:3,crystal:3},{crit:4},60],
["mana_rune","🔮","Руна маны","runesmith",8,{rune_shard:3,mana_crystal:2},{attack:5,defense:5},70]
];
const EN=[
["Лесной разбойник",90,12,18,0],["Рудничный голем",130,15,28,1],
["Рунный страж",180,20,45,2],["Драконий страж",260,28,80,3]
];
const esc=x=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function norm(){let e=E();e.res=e.res||{};e.prof=e.prof||{};for(const k in P)e.prof[k]=Object.assign({l:1,x:0},e.prof[k]||{});e.gear=Array.isArray(e.gear)?e.gear:[];e.runs=Object.assign({active:null,history:[]},e.runs||{});e.auction=Object.assign({listings:[],sales:[]},e.auction||{});e.contracts=Array.isArray(e.contracts)?e.contracts:[];e.ledger=Array.isArray(e.ledger)?e.ledger:[];e.daily=Object.assign({date:"",claimed:false},e.daily||{});return e}
function save(){S.saveNow?.();window.dispatchEvent(new CustomEvent("territory:economy-changed"))}
function add(k,n){let e=norm();e.res[k]=(e.res[k]||0)+n}
function xp(k,n){let e=norm(),p=e.prof[k];p.x+=n;while(p.l<300&&p.x>=p.l*100){p.x-=p.l*100;p.l++}}
function spend(o){let e=norm();for(const k in o)if((e.res[k]||0)<o[k])return false;for(const k in o)e.res[k]-=o[k];return true}
function start(id){let e=norm();if(e.runs.active)return false;let m=M.find(x=>x[0]===id);if(!m)return false;e.runs.active={loc:id,got:{},enc:false,started:Date.now()};save();render();return true}
function collect(){let e=norm(),r=e.runs.active;if(!r||r.enc)return false;let m=M.find(x=>x[0]===r.loc);if(!m)return false;m[4].forEach((x,i)=>{let q=1+Math.floor(Math.random()*(i?3:4));add(x[1],q);r.got[x[1]]=(r.got[x[1]]||0)+q});if(Math.random()<.38)r.enc=true;save();render();return true}
function fight(){let e=norm(),r=e.runs.active;if(!r||!r.enc)return false;let m=M.find(x=>x[0]===r.loc),idx=Math.max(0,M.indexOf(m)),cost=m[5],stones=+S.state.battleStones||0;if(stones<cost){pop("Боевые камни","Нужно: "+cost+". Получай их за задания, ежедневные награды и победы.");return false}S.state.battleStones=stones-cost;let z=EN[Math.min(idx,3)],level=+S.state.level||1,php=+S.state.hp||100,ehp=z[1]+level*2,turn=0;while(php>0&&ehp>0&&turn++<20){let hit=Math.max(4,Math.floor(8+level*1.2-z[4]*4+Math.random()*8));ehp-=hit;if(ehp<=0)break;php-=Math.max(3,z[2]-Math.floor(level/4)+Math.floor(Math.random()*5))}if(php<=0){S.state.hp=Math.max(1,Math.floor((S.state.maxHp||100)*.35));r.enc=false;r.paused=true;pop("Бой проигран","Бот остановил добычу. Восстановись и начни добычу снова.");}else{S.state.hp=Math.max(1,Math.floor(php));S.state.coins=(+S.state.coins||0)+z[3];r.enc=false;r.paused=false;add("battle_token",1);xp("blacksmith",10+idx*5);pop("Победа!","+"+z[3]+" 🪙 · +1 боевой жетон");}save();render();return true}
function craft(id){let e=norm(),q=REC.find(x=>x[0]===id);if(!q)return false;if(e.prof[q[3]].l<q[4]){pop("Профессия ещё не готова",P[q[3]][0]+" нужен уровень "+q[4]);return false}if(!spend(q[5])){pop("Не хватает материалов","Сначала отправься в нужную зону.");return false}e.gear.push({id:"gear_"+Date.now(),name:q[2],icon:q[1],profession:q[3],stats:q[6],rarity:q[4]>=8?"epic":q[4]>=5?"rare":"common",permanent:true,createdAt:Date.now()});xp(q[3],q[7]);save();render();return true}
function daily(){let e=norm(),d=new Date().toISOString().slice(0,10);if(e.daily.date===d&&e.daily.claimed){pop("Ежедневная награда","Сегодня уже получена.");return}e.daily.date=d;e.daily.claimed=true;S.state.battleStones=(+S.state.battleStones||0)+2;S.state.coins=(+S.state.coins||0)+50;save();pop("Ежедневная награда","🪨 +2 боевых камня · 🪙 +50");render()}
function stop(){let e=norm();if(!e.runs.active)return;e.runs.history.push(e.runs.active);e.runs.history=e.runs.history.slice(-30);e.runs.active=null;save();render()}
function pop(t,b){let m=document.getElementById("modal"),x=document.getElementById("modalBody");if(m&&x){x.innerHTML="<h2>"+esc(t)+"</h2><p>"+esc(b)+"</p>";m.classList.add("show")}}
function render(){let h=document.getElementById("world");if(!h)return;let e=norm(),r=e.runs.active,rows=Object.entries(e.res).filter(x=>x[1]>0).map(x=>"<span>"+esc(x[0])+"</span><b>"+(x[1]|0)+"</b>").join("");h.innerHTML='<header class="eco-head"><div><h1>🗺️ Мир Territory</h1><p>Добыча → бой → ресурсы → профессия → постоянный шмот</p></div><div class="eco-balance">🪙 '+(S.state.coins||0)+' · 🔵 '+(S.state.gems||0)+' · 🔴 '+(S.state.redGems||0)+' · 🪨 '+(S.state.battleStones||0)+'</div></header><div class="eco-actions"><button class="eco-btn" data-daily>🎁 Ежедневная награда</button></div><div class="eco-map">'+M.map(x=>'<button class="eco-location" data-l="'+x[0]+'"><strong>'+x[2]+' '+x[1]+'</strong><small>'+x[4].map(y=>y[0]).join(" · ")+'</small><em>Опасность: '+x[3]+' · 🪨 '+x[5]+'</em></button>').join("")+'</div><section class="eco-card"><h2>⛏️ Добыча</h2>'+(r?'<b>'+esc(M.find(x=>x[0]===r.loc)?.[1]||"Зона")+'</b><div class="eco-actions"><button class="eco-btn" data-c>⛏️ Добыть</button><button class="eco-btn" data-stop>⏹ Остановить</button></div>'+(r.enc?'<div class="eco-danger"><b>⚠️ Нападение бота!</b><p>Боевые камни расходуются только на этот бой.</p><button class="eco-btn" data-f>⚔️ Вступить в бой</button></div>':""):'<p>Выбери локацию.</p>')+'</section><section class="eco-grid"><div class="eco-card"><h2>📦 Ресурсы</h2><div class="eco-resources">'+(rows||"Пока пусто")+'</div></div><div class="eco-card"><h2>🔨 Профессии</h2>'+Object.entries(P).map(([k,p])=>'<div class="eco-row"><span>'+p[1]+' '+p[0]+'</span><b>'+e.prof[k].l+'/300</b></div>').join("")+'</div></section><section class="eco-card"><h2>⚒️ Мастерская</h2>'+REC.map(q=>'<div class="eco-row"><span>'+q[1]+' <b>'+q[2]+'</b><small> · '+P[q[3]][0]+' '+q[4]+'+<br>'+Object.entries(q[5]).map(x=>x[0]+" × "+x[1]).join(" · ")+'</small></span><button class="eco-btn" data-r="'+q[0]+'" '+(e.prof[q[3]].l<q[4]?"disabled":"")+'>Создать</button></div>').join("")+'</section><section class="eco-grid"><div class="eco-card"><h2>🏪 Аукцион</h2><p>Комиссия 10%. Серверная торговля подключается следующим этапом.</p></div><div class="eco-card"><h2>💼 Заказы мастерам</h2><p>Материалы игрока → цена → срок → репутация → готовый предмет.</p></div></section>';h.querySelectorAll("[data-l]").forEach(b=>b.onclick=()=>start(b.dataset.l));h.querySelector("[data-c]")?.addEventListener("click",collect);h.querySelector("[data-f]")?.addEventListener("click",fight);h.querySelector("[data-stop]")?.addEventListener("click",stop);h.querySelector("[data-daily]")?.addEventListener("click",daily);h.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>craft(b.dataset.r))}
norm();window.TerritoryEconomyFoundation={MAP:M,PROFESSIONS:P,RECIPES:REC,ensure:norm,startRun:start,collect,resolveEncounter:fight,stopRun:stop,addResource:add,addProfessionXp:xp,craft,render};
document.addEventListener("click",e=>{let b=e.target.closest('[data-home-action="sea"]');if(b){e.preventDefault();window.showScreen?.("world")}},true);window.addEventListener("territory:screen",e=>{if(e.detail==="world")render()});})();