(()=>{const S=window.TerritoryStore;if(!S||window.TerritoryEconomyFoundation)return;
const P={blacksmith:{name:"Кузнец",i:"⚒️",l:1,x:0},leatherworker:{name:"Кожевник",i:"🪡",l:1,x:0},jeweler:{name:"Ювелир",i:"💍",l:1,x:0},runesmith:{name:"Рунописец",i:"🔮",l:1,x:0}};
const M=[
["greenwood","Зелёный лес","🌲","Низкий",[["Древесина","wood"],["Смола","resin"],["Кожа","leather"]],1],
["ironmine","Железные рудники","⛏️","Низкий",[["Железная руда","iron_ore"],["Уголь","coal"],["Камень","stone"]],1],
["silverpeak","Серебряные вершины","🏔️","Средний",[["Серебро","silver_ore"],["Кристалл","crystal"],["Уголь","coal"]],1],
["runewastes","Рунические пустоши","🔮","Высокий",[["Осколок руны","rune_shard"],["Мана-кристалл","mana_crystal"],["Древняя пыль","ancient_dust"]],1],
["dragonvale","Долина драконов","🐉","Очень высокий",[["Чешуя дракона","dragon_scale"],["Кость дракона","dragon_bone"],["Огненное ядро","fire_core"]],2]
];
const R=[
["iron_blade","⚔️","Железный клинок","blacksmith",1,{iron_ore:4,coal:2},{attack:8},35],
["iron_guard","🛡️","Железный щит","blacksmith",3,{iron_ore:5,stone:2},{defense:10},45],
["forest_boots","🥾","Лесные сапоги","leatherworker",1,{leather:5,resin:2},{hp:12},35],
["crystal_ring","💍","Кристальное кольцо","jeweler",5,{silver_ore:3,crystal:3},{crit:4},60],
["mana_rune","🔮","Руна маны","runesmith",8,{rune_shard:3,mana_crystal:2},{attack:5,defense:5},70]
];
const E=()=>S.state.economy||(S.state.economy={v:4,res:{},prof:JSON.parse(JSON.stringify(P)),gear:[],runs:{active:null,history:[]},auction:{listings:[],sales:[]},contracts:[],ledger:[]});
const save=()=>{S.saveNow?.();window.dispatchEvent(new CustomEvent("territory:economy-changed"))};
const esc=x=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function xp(id,n){let e=E(),p=e.prof[id];if(!p)return;p.x+=n;while(p.l<300&&p.x>=p.l*100){p.x-=p.l*100;p.l++}}
function add(id,n){let e=E();e.res[id]=(e.res[id]||0)+n}
function spend(o){let e=E();for(let k in o)if((e.res[k]||0)<o[k])return false;for(let k in o)e.res[k]-=o[k];return true}
function start(id){let e=E();if(e.runs.active)return;let m=M.find(x=>x[0]==id);if(!m)return;e.runs.active={loc:id,got:{},enc:false};save();render()}
function collect(){let e=E(),r=e.runs.active;if(!r||r.enc)return;let m=M.find(x=>x[0]==r.loc);m[4].forEach((x,i)=>{let q=1+Math.floor(Math.random()*(i?3:4));add(x[1],q);r.got[x[1]]=(r.got[x[1]]||0)+q});if(Math.random()<.38)r.enc=true;save();render()}
function fight(){let e=E(),r=e.runs.active;if(!r||!r.enc)return;let m=M.find(x=>x[0]==r.loc),idx=M.indexOf(m),cost=m[5],st=+S.state.battleStones||0;if(st<cost){alert("Нужен боевой камень: "+cost);return}S.state.battleStones=st-cost;let enemy=[["Лесной разбойник",90,12,18],["Рудничный голем",130,15,28],["Рунный страж",180,20,45],["Драконий страж",260,28,80]][Math.min(idx,3)],hp=+S.state.hp||100,eh=enemy[1],pow=+S.state.level||1;for(let i=0;i<20&&hp>0&&eh>0;i++){eh-=Math.max(4,8+pow*1.2-(idx*4)+Math.random()*8);if(eh>0)hp-=Math.max(3,enemy[2]-Math.floor(pow/4)+Math.random()*5)}if(hp<=0){S.state.hp=Math.max(1,Math.floor((S.state.maxHp||100)*.35));r.enc=false;r.paused=true}else{S.state.hp=Math.floor(hp);S.state.coins=(+S.state.coins||0)+enemy[3];r.enc=false;r.paused=false;add("battle_token",1);xp("blacksmith",10+idx*5)}save();render()}
function craft(id){let e=E(),q=R.find(x=>x[0]==id);if(!q||e.prof[q[3]].l<q[4]||!spend(q[5]))return;let g={id:"gear_"+Date.now(),name:q[2],icon:q[1],profession:q[3],stats:q[6],permanent:true,rarity:q[4]>=8?"epic":q[4]>=5?"rare":"common"};e.gear.push(g);xp(q[3],q[7]);save();render()}
function list(id,price,c="coins"){let e=E(),g=e.gear.find(x=>x.id==id);if(!g)return;let l={id:"lst_"+Date.now(),itemId:id,price:+price,currency:c,status:"active"};e.auction.listings.push(l);save();return l}
function sell(id){let e=E(),l=e.auction.listings.find(x=>x.id==id&&x.status=="active");if(!l)return;let fee=l.price*.1;l.status="sold";e.auction.sales.push({listingId:id,gross:l.price,fee,net:l.price-fee});save()}
function render(){let h=document.getElementById("world");if(!h)return;let e=E(),r=e.runs.active,res=Object.entries(e.res).filter(x=>x[1]>0).map(x=>`<span>${esc(x[0])}</span><b>${x[1]|0}</b>`).join("");h.innerHTML=`<header class="eco-head"><div><h1>🗺️ Мир Territory</h1><p>Добыча → бот → ресурсы → мастер → постоянный шмот</p></div><div class="eco-balance">🪙 ${S.state.coins||0} · 🔵 ${S.state.gems||0} · 🔴 ${S.state.redGems||0} · 🪨 ${S.state.battleStones||0}</div></header><div class="eco-note">Боевые камни расходуются только на опасные встречи. Предметы, созданные мастером, постоянные.</div><div class="eco-map">${M.map(x=>`<button class="eco-location" data-l="${x[0]}"><strong>${x[2]} ${x[1]}</strong><small>${x[4].map(y=>y[0]).join(" · ")}</small><em>Опасность: ${x[3]} · 🪨 ${x[5]}</em></button>`).join("")}</div><section class="eco-card"><h2>⛏️ Добыча</h2>${r?`<b>${M.find(x=>x[0]==r.loc)[1]}</b><div class="eco-actions"><button class="eco-btn" data-c>⛏️ Добыть</button><button class="eco-btn" data-stop>⏹ Остановить</button></div>${r.enc?`<div class="eco-danger"><b>⚠️ Нападение бота!</b><p>Победи его, чтобы продолжить.</p><button class="eco-btn" data-f>⚔️ Вступить в бой</button></div>`:""}`:"<p>Выбери локацию выше.</p>"}</section><section class="eco-grid"><div class="eco-card"><h2>📦 Ресурсы</h2><div class="eco-resources">${res||"Пока пусто"}</div></div><div class="eco-card"><h2>🔨 Профессии</h2>${Object.entries(P).map(([k,p])=>`<div class="eco-row"><span>${p.i} ${p.name}</span><b>${e.prof[k].l}/300</b></div>`).join("")}</div></section><section class="eco-card"><h2>⚒️ Мастерская</h2>${R.map(q=>`<div class="eco-row"><span>${q[1]} <b>${q[2]}</b><small> · ${P[q[3]].name} ${q[4]}+<br>${Object.entries(q[5]).map(x=>x[0]+" × "+x[1]).join(" · ")}</small></span><button class="eco-btn" data-r="${q[0]}" ${e.prof[q[3]].l<q[4]?"disabled":""}>Создать</button></div>`).join("")}</section><section class="eco-grid"><div class="eco-card"><h2>🏪 Аукцион</h2><p>Комиссия сделки: 10%. Предмет нельзя продать дважды.</p></div><div class="eco-card"><h2>💼 Заказ мастеру</h2><p>Серверный заказ: материалы → цена → срок → репутация → готовый предмет.</p></div></section>`;h.querySelectorAll("[data-l]").forEach(b=>b.onclick=()=>start(b.dataset.l));h.querySelector("[data-c]")?.addEventListener("click",collect);h.querySelector("[data-f]")?.addEventListener("click",fight);h.querySelector("[data-stop]")?.addEventListener("click",()=>{e.runs.history.push(r);e.runs.active=null;save();render()});h.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>craft(b.dataset.r))}
E().prof=Object.assign(JSON.parse(JSON.stringify(P)),E().prof||{});E().res=E().res||{};E().gear=E().gear||[];E().runs=E().runs||{active:null,history:[]};E().auction=E().auction||{listings:[],sales:[]};
window.TerritoryEconomyFoundation={MAP:M,PROFESSIONS:P,RECIPES:R,startRun:start,collect,resolveEncounter:fight,stopRun:()=>{let e=E();e.runs.active=null;save();render()},addResource:add,addProfessionXp:xp,craft,createListing:list,recordSale:sell,render};
document.addEventListener("click",e=>{let b=e.target.closest('[data-home-action="sea"]');if(b){e.preventDefault();window.showScreen?.("world")}},true);
window.addEventListener("territory:screen",e=>{if(e.detail=="world")render()});
})();