(function(){
'use strict';
const S=()=>window.TerritoryStore?.state||{};
const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ATTRS=[['strength','💪','Сила'],['agility','🪽','Ловкость'],['intuition','👁️','Интуиция'],['resilience','🛡️','Стойкость'],['constitution','❤️','Конституция']];
const STYLES={crit:{title:'Критический удар',icon:'💥',text:'Упор на высокий шанс и урон критического удара.'},dodge:{title:'Уворот',icon:'💨',text:'Упор на ловкость и уклонение от атак.'},tank:{title:'Танк',icon:'🛡️',text:'Упор на здоровье, защиту и блок.'},resilience:{title:'Стойкость',icon:'🧱',text:'Упор на выживаемость и сопротивление.'}};
const PROFESSIONS={blacksmith:['Кузнец','⚒️'],leatherworker:['Кожевник','🪡'],jeweler:['Ювелир','💍'],runesmith:['Рунописец','🔮']};
const SKINS=[
 ['male-1','Мужской образ 1','male','assets/skins/male-1.svg'],['male-2','Мужской образ 2','male','assets/skins/male-2.svg'],['male-3','Мужской образ 3','male','assets/skins/male-3.svg'],['male-4','Мужской образ 4','male','assets/skins/male-4.svg'],['male-5','Мужской образ 5','male','assets/skins/male-5.svg'],
 ['female-1','Женский образ 1','female','assets/skins/female-1.svg'],['female-2','Женский образ 2','female','assets/skins/female-2.svg'],['female-3','Женский образ 3','female','assets/skins/female-3.svg'],['female-4','Женский образ 4','female','assets/skins/female-4.svg'],['female-5','Женский образ 5','female','assets/skins/female-5.svg']
];
function ensure(){const s=S();s.character=s.character||{};const c=s.character;c.strength=Number(c.strength)||10;c.agility=Number(c.agility)||10;c.intuition=Number(c.intuition)||10;c.resilience=Number(c.resilience)||10;c.constitution=Number(c.constitution)||10;c.freePoints=Number.isFinite(Number(c.freePoints))?Math.max(0,Number(c.freePoints)):Math.max(0,(Number(s.level)||1)-1);c.specialization=STYLES[c.specialization]?c.specialization:'crit';c.profession=c.profession&&PROFESSIONS[c.profession]?c.profession:'blacksmith';c.clan=c.clan||{name:'Северный клан',role:'Участник'};c.skin=c.skin||'female-1';c.ownedSkins=Array.isArray(c.ownedSkins)?c.ownedSkins:['female-1'];c.uniqueSets=Array.isArray(c.uniqueSets)?c.uniqueSets:['unique-dikaya'];c.activeUnique=c.activeUnique||'';c.follower=c.follower||{name:'Белый тигр',level:1,icon:'🐯',hp:100,attack:25,defense:18};return c}
function xpStat(){const c=ensure(),s=S();return {hp:Number(s.maxHp||100)+c.constitution*12,attack:125+(Number(s.level)||1)*2+c.strength*3,defense:98+(Number(s.level)||1)+c.resilience*3,crit:8+c.intuition*.55,dodge:5+c.agility*.5,block:3+c.resilience*.35,energy:Number(s.maxEnergy||100),speed:100+c.agility*.7,resistance:4+c.resilience*.4};}
function addPoint(k){const c=ensure();if(c.freePoints<1)return toast('Нет свободных очков. Получи новый уровень.');c[k]++;c.freePoints--;window.TerritoryStore.saveNow();renderOwn();toast('Характеристика повышена: '+ATTRS.find(a=>a[0]===k)[2]);}
function toast(t){let x=$('.tp-toast');if(!x){x=document.createElement('div');x.className='tp-toast';document.body.appendChild(x)}x.textContent=t;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),1800)}
function equip(){const s=S(),arr=Array.isArray(s.equipment)?s.equipment:[];const names=['Шлем','Ожерелье','Плащ','Броня','Сапоги','Оружие','Аксессуар'];const out=arr.slice(0,7);while(out.length<7)out.push(null);return out.map((it,i)=>({it,name:names[i]}));}
function charImage(){const c=ensure();if(c.activeUnique==='unique-dikaya')return 'assets/skins/unique-dikaya.png';const x=SKINS.find(v=>v[0]===c.skin);return x?x[3]:'assets/ui/profile.png'}
function slotHTML(side){const e=equip();const list=side==='left'?e.slice(0,4):e.slice(4,7);return '<div class="tp-eq-col">'+list.map((x,i)=>{const it=x.it;return `<button class="tp-eq-slot ${it?'':'empty'}" title="${esc(x.name)}">${it?.icon&&/^https?:|^assets\//.test(String(it.icon))?`<img src="${esc(it.icon)}" alt="">`:`<span class="tp-eq-emoji">${esc(it?.icon||['🪖','📿','🧥','🛡️','🥾','⚔️','💍'][side==='left'?i:i+4])}</span>`}<em>${it?.level?'+'+esc(it.level):it?'':'—'}</em></button>`}).join('')+'</div>'}
function topInfo(publicMode){const s=S(),p=s.profile||{},c=ensure();return `<div class="tp-hero-top"><div class="tp-avatar"><img src="${esc(p.photoUrl||'assets/ui/profile.png')}" alt=""></div><div><div class="tp-name">${esc(p.displayName||'Игрок')}</div><div class="tp-meta">Уровень ${Number(s.level)||1} · VIP ${Number(p.vip)||0}</div><div class="tp-meta">🛡️ <b>${esc(c.clan.name)}</b></div></div><div class="tp-rank"><div class="medal">🏆</div><small>Рейтинг</small><strong>ТОП 100</strong></div></div>`}
function attrs(publicMode){const c=ensure();return `<section class="tp-section"><div class="tp-section-title"><span>⚔️ Характеристики</span><span class="tp-free">Свободные очки: ${c.freePoints}</span></div><div class="tp-attrs">${ATTRS.map(([k,ico,n])=>`<div class="tp-attr"><span class="ico">${ico}</span><small>${n}</small><strong>${c[k]}</strong>${publicMode?'':`<button class="tp-plus" data-add-stat="${k}" ${c.freePoints<1?'disabled':''}>＋</button>`}</div>`).join('')}</div><div class="tp-special"><span>Специализация: </span><strong>${STYLES[c.specialization].icon} ${STYLES[c.specialization].title}</strong><small>${STYLES[c.specialization].text}</small></div></section>`}
function info(publicMode){const s=S(),c=ensure(),pr=PROFESSIONS[c.profession],p=s.profile||{};return `<section class="tp-section"><div class="tp-section-title">👤 Основная информация</div><div class="tp-grid2"><div class="tp-info"><div class="tp-row"><span>Имя</span><b>${esc(p.displayName||'Игрок')}</b></div><div class="tp-row"><span>Уровень</span><b>${s.level||1}</b></div><div class="tp-row"><span>VIP</span><b>${p.vip||0}</b></div><div class="tp-row"><span>Статус</span><b>● Онлайн</b></div></div><div class="tp-info"><div class="tp-row"><span>Профессия</span><b>${pr[1]} ${pr[0]}</b></div><div class="tp-row"><span>Уровень проф.</span><b>${s.economy?.prof?.[c.profession]?.l||1}/300</b></div><div class="tp-row"><span>Клан</span><b>${esc(c.clan.name)}</b></div><div class="tp-row"><span>Роль</span><b>${esc(c.clan.role)}</b></div></div></div></section>`}
function combat(publicMode){const s=S(),t=xpStat();return `<section class="tp-section"><div class="tp-section-title">⚔️ Параметры боя</div><div class="tp-stat-grid"><div class="tp-stat"><span>❤️ Здоровье</span><b>${Math.round(t.hp)}</b></div><div class="tp-stat"><span>⚔️ Атака</span><b>${Math.round(t.attack)}</b></div><div class="tp-stat"><span>⚡ Энергия</span><b>${Math.round(t.energy)}</b></div><div class="tp-stat"><span>🛡️ Защита</span><b>${Math.round(t.defense)}</b></div><div class="tp-stat"><span>💥 Крит. шанс</span><b>${t.crit.toFixed(1)}%</b></div><div class="tp-stat"><span>💥 Крит. урон</span><b>${capped(150+(ensure().intuition*1.2))}%</b></div><div class="tp-stat"><span>💨 Уклонение</span><b>${t.dodge.toFixed(1)}%</b></div><div class="tp-stat"><span>🛡️ Блок</span><b>${t.block.toFixed(1)}%</b></div><div class="tp-stat"><span>🧱 Сопротивление</span><b>${t.resistance.toFixed(1)}%</b></div><div class="tp-stat"><span>⚡ Скорость</span><b>${Math.round(t.speed)}</b></div></div>${publicMode?'':'<div class="tp-own-note">Ресурсы аккаунта здесь не показываются другим игрокам.</div>'}</section>`}
function capped(x){return Math.round(x)}
function achievements(){const s=S();return `<section class="tp-section"><div class="tp-section-title">🏆 Достижения</div><div class="tp-ach"><div>⚔️ PvP<strong>${s.arena?.wins||0}</strong></div><div>☠️ Боссы<strong>${s.pve?.bossDefeated||0}</strong></div><div>⚔️ PvE<strong>${s.pve?.wins||0}</strong></div></div></section>`}
function follower(){const c=ensure(),f=c.follower;return `<section class="tp-section"><div class="tp-section-title">🐾 Последователь</div><div class="tp-follower"><div style="font-size:46px;text-align:center">${esc(f.icon||'🐯')}</div><div><b>${esc(f.name)}</b><small>Уровень ${f.level}</small></div><div class="tp-mini-stats">❤️ <b>${f.hp}</b><br>⚔️ <b>${f.attack}</b><br>🛡️ <b>${f.defense}</b></div></div></section>`}
function renderOwn(){const h=$('#hero');if(!h)return;const c=ensure();h.className='screen panel tp-screen active';h.innerHTML=`<div class="tp-wrap"><header class="tp-head"><button class="tp-back" data-tp-back>‹</button><div><div class="tp-top">Territory</div><h1>Профиль игрока</h1></div><span style="width:42px"></span></header><section class="tp-hero">${topInfo(false)}<div class="tp-stage"><div class="tp-stage-bg"></div><img class="tp-character" src="${charImage()}" alt="Персонаж"><div class="tp-equip">${slotHTML('left')}${slotHTML('right')}</div></div></section>${info(false)}${attrs(false)}${combat(false)}<div class="tp-prof-clan"><div class="tp-card"><h3>⚗️ Профессия</h3><p>${PROFESSIONS[c.profession][1]} <b>${PROFESSIONS[c.profession][0]}</b></p><p>Уровень: <b>${S().economy?.prof?.[c.profession]?.l||1}/300</b></p></div><div class="tp-card"><h3>🛡️ Клан</h3><p><b>${esc(c.clan.name)}</b></p><p>Роль: ${esc(c.clan.role)}</p></div></div>${achievements()}${follower()}<div class="tp-actions"><button class="tp-btn" data-open-salon>💎 Салон красоты</button><button class="tp-btn dark" data-open-top>🏆 ТОП 100</button></div><div class="tp-scroll-hint">Листай вниз — профиль продолжается</div></div>`;bindProfile();}
function renderPublic(data){const h=$('#hero');if(!h)return;const s=S(),c=ensure();const d=data||{};const pc=Object.assign({},c,d.character||{});const pp=Object.assign({},s.profile,d.profile||{});const ps=Object.assign({},s,d);h.className='screen panel tp-screen tp-public active';h.innerHTML=`<div class="tp-wrap"><header class="tp-head"><button class="tp-back" data-tp-back>‹</button><div><div class="tp-top">ТОП 100</div><h1>Профиль игрока</h1></div><span style="width:42px"></span></header><section class="tp-hero"><div class="tp-hero-top"><div class="tp-avatar"><img src="${esc(pp.photoUrl||'assets/ui/profile.png')}" alt=""></div><div><div class="tp-name">${esc(pp.displayName||'Игрок')}</div><div class="tp-meta">Уровень ${ps.level||1} · VIP ${pp.vip||0}</div><div class="tp-meta">🛡️ <b>${esc(pc.clan?.name||'Без клана')}</b></div></div><div class="tp-rank"><div class="medal">🏆</div><small>Рейтинг</small><strong>ТОП ${d.rank||100}</strong></div></div><div class="tp-stage"><div class="tp-stage-bg"></div><img class="tp-character" src="${d.skinImage||'assets/ui/profile.png'}" alt="Персонаж"><div class="tp-equip">${slotHTML('left')}${slotHTML('right')}</div></div></section><section class="tp-section"><div class="tp-section-title">👤 Основная информация</div><div class="tp-grid2"><div class="tp-info"><div class="tp-row"><span>Имя</span><b>${esc(pp.displayName||'Игрок')}</b></div><div class="tp-row"><span>Уровень</span><b>${ps.level||1}</b></div><div class="tp-row"><span>VIP</span><b>${pp.vip||0}</b></div></div><div class="tp-info"><div class="tp-row"><span>Профессия</span><b>${PROFESSIONS[pc.profession]?.[1]||'⚗️'} ${PROFESSIONS[pc.profession]?.[0]||'—'}</b></div><div class="tp-row"><span>Клан</span><b>${esc(pc.clan?.name||'—')}</b></div></div></div></section><section class="tp-section"><div class="tp-section-title">⚔️ Характеристики</div><div class="tp-attrs">${ATTRS.map(([k,ico,n])=>`<div class="tp-attr"><span class="ico">${ico}</span><small>${n}</small><strong>${pc[k]||0}</strong><span></span></div>`).join('')}</div><div class="tp-special"><span>Специализация: </span><strong>${STYLES[pc.specialization]?.icon||'⚔️'} ${STYLES[pc.specialization]?.title||'—'}</strong></div></section>${combat(true)}${achievements()}${follower()}<div class="tp-scroll-hint">Листай вниз — всё остальное ниже</div></div>`;bindProfile();}
function renderTop(){const h=$('#hero');if(!h)return;h.className='screen panel tp-screen active';const s=S(),p=s.profile||{};h.innerHTML=`<div class="tp-wrap"><header class="tp-head"><button class="tp-back" data-tp-back>‹</button><div><div class="tp-top">Territory</div><h1>ТОП 100</h1></div><span style="width:42px"></span></header><section class="tp-section"><div class="tp-section-title">🏆 Рейтинг игроков</div><div class="tp-top100"><button class="tp-rank-row" data-open-player="self"><strong>1</strong><img src="${esc(p.photoUrl||'assets/ui/profile.png')}"><span><strong>${esc(p.displayName||'Игрок')}</strong><small>Ваш профиль · уровень ${s.level||1}</small></span><em>Мой профиль</em></button></div><div class="tp-own-note">Реальный ТОП 100 будет заполняться серверными данными. Здесь нет выдуманных балансов или ресурсов.</div></section></div>`;h.querySelector('[data-open-player]')?.addEventListener('click',()=>renderOwn());}
function renderSalon(){const h=$('#salon');if(!h)return;const c=ensure();h.className='screen panel tp-screen active';h.innerHTML=`<div class="tp-wrap"><header class="tp-head"><button class="tp-back" data-tp-back>‹</button><div><div class="tp-top">Карта Territory</div><h1>💎 Салон красоты</h1></div><span style="width:42px"></span></header><section class="tp-section tp-salon"><div class="tp-salon-hero"><img class="tp-salon-preview" src="assets/skins/unique-dikaya.png"><div><h2>⭐ Уникальный комплект «Дикая»</h2><p>Готовый индивидуальный образ: персонаж + визуальный комплект + белый тигр.</p><button class="tp-btn" data-unique>⭐ Открыть комплект</button></div></div><div class="tp-paywall">✨ Индивидуальный образ за реальные деньги остаётся косметическим: он не даёт боевых преимуществ.</div><div class="tp-tabs"><button class="active" data-gender="female">👩 Женские</button><button data-gender="male">👨 Мужские</button><button data-gender="unique">⭐ Уникальные</button></div><div class="tp-look-grid" id="tpLookGrid"></div><div class="tp-salon-note">Стандартные образы доступны без покупки. Уникальный редактор в будущем создаёт внешний вид, который закрепляется только за этим игроком.</div></section></div>`;paintLooks('female');bindSalon();}
function paintLooks(g){const host=$('#tpLookGrid');if(!host)return;const c=ensure();let list=SKINS.filter(x=>x[2]===g);if(g==='unique')list=[['unique-dikaya','Комплект «Дикая»','unique','assets/skins/unique-dikaya.png']];host.innerHTML=list.map(x=>`<button class="tp-look ${x[2]==='unique'?'tp-unique':''} ${c.skin===x[0]?'active':''}" data-skin="${x[0]}"><img src="${x[3]}" alt=""><b>${esc(x[1])}</b><small>${x[2]==='unique'?'⭐ Премиальный индивидуальный комплект':'Стандартный образ'}</small>${x[2]==='unique'?'<span class="tp-price">Премиум</span>':''}</button>`).join('');}
function selectSkin(id){const c=ensure();if(id==='unique-dikaya'){toast('⭐ Комплект «Дикая» — премиальный. Оплата будет подключена через сервер.');return}c.activeUnique='';c.skin=id;if(!c.ownedSkins.includes(id))c.ownedSkins.push(id);window.TerritoryStore.saveNow();toast('Образ выбран');renderSalon();}
function bindSalon(){document.querySelectorAll('[data-gender]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-gender]').forEach(x=>x.classList.remove('active'));b.classList.add('active');paintLooks(b.dataset.gender)});document.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>selectSkin(b.dataset.skin));document.querySelector('[data-unique]')?.addEventListener('click',()=>selectSkin('unique-dikaya'));}
function bindProfile(){document.querySelectorAll('[data-add-stat]').forEach(b=>b.onclick=()=>addPoint(b.dataset.addStat));document.querySelector('[data-open-salon]')?.addEventListener('click',()=>openSalon());document.querySelector('[data-open-top]')?.addEventListener('click',()=>renderTop());document.querySelector('[data-tp-back]')?.addEventListener('click',()=>window.TerritoryUI?.show?.('home'))}
function openSalon(){window.showScreen?.('salon');renderSalon()}
function openOwn(){window.showScreen?.('hero');renderOwn()}
function openTop(){window.showScreen?.('hero');renderTop()}
window.TerritoryProfile={open:openOwn,openTop,openPublic:renderPublic,openSalon,ensure,addPoint,render:renderOwn};
window.addEventListener('territory:level-up',e=>{const c=ensure();c.freePoints+=Math.max(1,Number(e.detail?.levels)||1);window.TerritoryStore.saveNow();if(document.body.dataset.screen==='hero')renderOwn()});
document.addEventListener('click',e=>{const a=e.target.closest('[data-home-action]');if(!a)return;const k=a.dataset.homeAction;if(k==='hero'){e.preventDefault();e.stopPropagation();openOwn()}if(k==='trophy'){e.preventDefault();e.stopPropagation();openTop()}if(k==='beauty'){e.preventDefault();e.stopPropagation();openSalon()}},true);
window.addEventListener('territory:screen',e=>{if(e.detail==='hero'&&document.querySelector('#hero'))setTimeout(renderOwn,0);if(e.detail==='salon')setTimeout(renderSalon,0)});
window.addEventListener('territory:state-changed',()=>{if(document.body.dataset.screen==='hero'&&!document.querySelector('.tp-public'))renderOwn()});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{ensure();injectSalon();}, {once:true}); else {ensure();injectSalon()}
function injectSalon(){if(!$('#salon')){const sec=document.createElement('section');sec.id='salon';sec.className='screen panel tp-screen';$('#app')?.appendChild(sec)}const map=$('#map');if(map&&!map.querySelector('[data-home-action="beauty"]')){const box=map.querySelector('.road-actions');if(box){const b=document.createElement('button');b.className='dark-btn';b.dataset.homeAction='beauty';b.textContent='💎 Салон красоты';box.appendChild(b)}}}
})();
